apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: func-ebill
  namespace: default
spec:
  createingress: true
  functionref:
    functionweights: null
    name: func-ebill
    type: name
  host: ""
  ingressconfig:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dongfg
    host: ebill.func.dongfg.com
    path: /
    tls: tls-ebill-func-dongfg
  method: ""
  methods:
  - GET
  - POST
  prefix: ""
  relativeurl: /{Subpath}
